### ISSUE TITLE
resources/concepts incomplete

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#122]
Several concepts from here ...

https://github.com/101companies/101repo/tree/master/concepts

... are not here ...

http://101companies.org/resources/concepts/?format=html

For instance, "Function".

Something's not working.

**Comment by martinleinberger** [comment]
_Function_ is in the list.

What I can't find is Binary_search, Hello_world_program, Linear_search, Linked_list and Quicksort. This is because they are not in the [wiki dump](http://data.101companies.org/dumps/Wiki101Full.json).

The wiki dump provides the members of a namespace to the discovery service.

**Comment by rlaemmel** [comment]
Yes, sorry for the confusion.
Function is in the list, but the Main.hs file from 101repo is not listed.
Yes, some other concepts are missing entirely.
I added them 2-3 days ago. 
So they should all be there by now.

**Comment by martinleinberger** [comment]
This was because 101results/101repo was out of sync. More details are [here](https://github.com/101companies/101worker/issues/79).
This is fixed. 

As for the wiki issue, I'm reassigning this to @avaranovich - they will show up in the discovery service once they show up in the wiki dump (and the members module ran through).

**Comment by avaranovich** [comment]
@martinleinberger reassigning this issue back to you, since the concepts you mention are now in the wikidump. It was failing 2 days because of the url change. I closed a related issue.

**Comment by martinleinberger** [comment]
After running the members module, the concepts can now be found.
