### ISSUE TITLE
Allow fragment description from within wiki pages

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#26]
That's something Martin and me discussed today and this may be the right direction.

Let's discuss this some more.
# The past

We have played around with different ways of including code snippets into wiki pages.
### Pros
- Easy in the sense that authors are productive this way.
- One can easily customize the code for what needs to be shown.
### Cons
- Code may be outdated.
- This is not necessary traceable for users.
- The ability to change may be overused rather than improving the original code.
### Pros
- Provides some traceability.
### Cons
- This is not enforced currently.
- The precise origin is not tracked and cannot be checked thus.
- All other cons as previously
# Other options
## Literate programming

We could write the contributions in the style of literate programming (by merging code and documentation, in fact, by embedding comments into code) so that wiki pages are automagically extracted.
### Pros
- Best practices in some contexts
### Cons
- Disruptive
- Hard to apply to systems (as opposed to programs)

We believe that this style would effectively disrupt some valuable aspects of a separation of code and documentation in our case. Specifically, "editing code on the wiki" is not realistic as the systems need to be developed in an IDE. Also, "editing documentation in the code/IDE" is also not realistic because wiki users need to see changes immediately and also get help from the wiki system. Perhaps most importantly, we would like to decouple the activities of content authoring and developing code. 

Arguably, we need a form of literate programming, which may not be established and straightforward. Specifically, we deal with systems rather than programs. The wiki pages are never meant to provide a sort of comprehensive documentation of the system. Instead, the wiki pages are supposed to do cherry picking in a way that it is not so clear how to approach this issue with literate programming.
## 101meta rules for fragment descriptions

The source code of a contribution could be prepared by using existing, 101meta-based means of fragment description to point out fragments of interest. These fragments could be associated with symbolic ids, using again metadata so that they can be referred to from within the wiki pages or from anywhere for that matter. We would rely on some services in the wiki system which look up the corresponding fragments while rendering the pages.
### Pros
- Leverage existing means of addressing fragments.
- Source code is not affected as the rules would be separate from source code.
- Symbolic ids would be easily used in the wiki markup.
### Cons
- Low productivity with existing tools: authoring tools take time.
- Low traceability with existing tools; code owners and others may miss fragments.
## Mark fragments within the actual source files

Using some comment-based convention, as in "begin CUT ... end CUT", relevant fragments could be marked and associated with a symbolic id, which then could referred to within wiki pages, as discussed above.
### Pros
- Good productivity: we can easily edit files that way
- Good traceability: we can easily see those markers.
### Cons
- The markers may actually obfuscate the code.
## Embed fragment descriptions into wiki pages

Using some special markup, we could describe the relevant fragments directly on the wiki pages, where they are needed. The markup would need to enable the following ingredients:
- Name of the source file
- Perhaps code for syntax highlighting (if this cannot be inferred externally)
- Fragment description for fragment to be shown in place of markup (coded up in JSON).
### Pros
- Good coupling: The content author is likely the one who discovers the fragments of interest and thus should write them down, as they are found. 
- Good descriptiveness: The fragment descriptions are also self-contained enough to help content authors being reminded of what's selected.
- No code obfuscation: the code does not to be changed just for the sake of being addressed from within the wiki pages.
### Cons

To be determined
# Intermediate conclusion

We need to discuss, but the last option appears preferable.

Technically, this would require capabilities as follows:
- The wiki markup would need to support fragment descriptions.
- The wiki C/S part would need to be able to request source code for fragments and render it with basic syntax highlighting.
- The existing fragment location infrastructure (currently part of 101worker) would need to be invoked as a service. There is a corresponding issue for that on the 101worker repo.

**Comment by rlaemmel** [comment]
Andrei and me had a great discussion earlier today (eem, yesterday) which we should continue with all those involved on Monday.

Here is the bottom line.

We may want to simplify and more RDF/URI-enable the treatment of fragments.

Consider this sort of contrived example:

http://repo.101companies.com/contributions/javaComposition/org/softlang/model/Company.java/total

"repo.101companies.com" would resolve to the handler for file/fragment lookup for 101repo.

"contributions/javaComposition/org/softlang/model/Company.java" is the local URL for the source file.

"total" is the fragment locator within the file.

This would be easy to write and easy to serve.

Perhaps, more importantly, it would fully resource-ify fragments.

Thus, we get closer to this wonderful RDF-enabled world.

**Comment by martinleinberger** [comment]
I have a prototype up and running on my local machine. However, there are two issues that may need some discussion:

First of all, FragmentLocators work on files; they expect all parameters to be files. So this service needs to take the given fragment, save the data as a file, then call the FragmentLocator and then read the file that the FragmentLocator produced. This could be simplified if FragmentLocators would be extended so that they can also take the Fragment directly from the command line and write the output in the console. 

The second thing is - different FragmentLocators expect different input. JFragmentLocator will except a classname and a methodname (overloading is optional), so the RDF-ish description would look like "somePath/Company.java/Company/total". This would be taken apart into "class : Company" and "method : total". The Haskell FragmentLocator takes a function. So it would be "somePath/Cut.hs/cut" that is taken apart into "function : cut". I can think of two ways to deal with it:
First option is that FragmentLocators also need to provide the option to be given a URL fragment description (Company/total in the Java case, just cut in the Haskell Case), because they should know what infos to extract from that. 
Second option is an Indirection Layer in the service, that acts as an wrapper and knows how to take the fragment apart for every FragmentLocator. This would imply that the author of a new FragmentLocator would also need to add new functionality to this indirection layer.

**Comment by martinleinberger** [comment]
To summarize the results of todays scrum:
- FragmentLocators should also allow the option to work entirely with the command line. For example, such a call could look like: **./somePath/locator.py path/to/File fragmentData** and the result should be printed on the **command line** instead of a file.
- FragmentLocators should also accept the fragment specific part of the RDF-ish URI, because they know best how to handle it. For example, for **contributions/javaComposition/org/softlang/model/Company.java/Company/total**, the fragment specific part would be **Company/total**.
