### ISSUE TITLE
It looks like subsubsections make the wiki parser panic

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#260]
I am just looking at:

http://mediawiki.101companies.org/wiki/index.php?title=Feature:Editing&action=edit

It has (as of filing this issue) subsubsections, i.e., "==== ... ====".

Everything from the first quadruple = onwards is not rendered on the new wiki.

I am now removing subsubsections, but "====" needs to be supported or at least the parser needs to ignore it or handle it like "===".

**Comment by tschmorleiz** [comment]
This is a parsing issue indeed :) : 
Look here: 

http://101companies.org/api/pages/Feature%3AEditing

and pay attention to the content of the "Details" section. The Metadata section is within the section content. So the parser fails to split this content into proper sections. 

What I do on the client is check if a section only contains one top-section header. Otherwise validation fails. Therefore here the "Details" section (also containing the "Metadata" section) is not rendered.

**Comment by rlaemmel** [comment]
@tschmorleiz 

What is the conclusion here? I don't understand your response. Is this issue to be closed?

Thanks,
Ralf

**Comment by tschmorleiz** [comment]
Fixed by fixing #308.

**Comment by tschmorleiz** [comment]
Actually seems to be unrelated.

**Comment by tschmorleiz** [comment]
Now fixed, some tiny bug in the stack-based parsing of sections :) For demonstration I changed http://101companies.org/wiki/Feature:Editing back to using "====".
