### ISSUE TITLE
namespace injections get deleted upon save (occasionally)

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#280]
cc @avaranovich 

Look here, for example, how it looks like after save:

http://101companies.org/wiki/Zipper%20monad

There was a suitable instanceOf::Namespace:Concept in the metadata section when I pushed "save".

**Comment by rlaemmel** [comment]
I can't say for sure, but it feels like the instanceOf is deleted when its there and then injected again during the next save. So it is sort of alternating it seems.

**Comment by burgua** [comment]
Actually every Page  on wiki has concept now. 
E.g. **Contribution:Fsharp** has namespace **Contribution**.
If namespace is not specified (e.g. **Monad**) page will  take default namespace **Concept**.
That's why you have namespace on every save. 
Here is this page in db http://101companies.org/admin/page/51b88c3cb8bc1afe42000347
Is this automatically definition of namespace bad?

**Comment by burgua** [comment]
@tschmorleiz I actually don't get the logic there, but it works using code mentioned above. Could you merge it if it's ok?

**Comment by tschmorleiz** [comment]
Branch did not solve the problem for me. Fixed.

(Problem was "content -> self.content" here https://github.com/101companies/101rails/commit/875ea167fb79a1ceac3582ce9ce81771ece07a85#L2R187)
