### ISSUE TITLE
repo folder selection need to scale

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#367]
cc @burgua 

When one selects the folder in the wiki like here ...

![image](https://cloud.githubusercontent.com/assets/1208815/2780531/9870b5e2-cb08-11e3-8f24-e42fe698d317.png)

... then this need to be done in the common hierarchical fashion as in file explorers because otherwise it is way to hard to find a specific folder for a complex directory tree. For instance , in the example above I was trying to select a particular subfolder of contributions but it is very hard to scroll down there.

**Comment by burgua** [comment]
We have already thought about that problem and that's why implemented in this way. It's not a simple select, but more intelligent control. In input field of this control you can start to type name of the folder (or part of the name) and outputted folders will be filtered. 

Using "file explorer" way is not the best case for using GitHub API. We have limitation on using it according to https://developer.github.com/v3/rate_limit . In current approach we use only 3 API requests to get folders for one repo. This helps us to spare API requests. 

Some repo contains also too much folders (e.g. 101repo) to be represented nice in "explorer way".

And here is some demonstration, how it works
https://dl.dropboxusercontent.com/u/795699/case1.mp4 

Please close, if it's ok.
