### ISSUE TITLE
Please low-level document the backup mechanism

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#400]
cc @burgua 

As you told me, you are about to set up a cron job zip up and commit the db to 101backup with user 101commit. There is a certain way to roll back changes by unzipping and deploying. So please point to scripts and all other information that can help people.

**Comment by burgua** [comment]
# Description

Entire backup of MongoDB is made as zip archive of result of [mongorestore](http://docs.mongodb.org/manual/reference/program/mongorestore/) command secured with **password**.

As **password** was used the standard @101companies password.

Backup is made every day at 3:00 and pushed to [GitHub repo](https://github.com/101companies/101zip) as user @101commit.

# Additional functionality

Were made two Rake tasks:
- push_production_db_to_github
- import_production_db_to_local_dev_db

The first one make commit of backup to GitHub.

The second imports production MongoDB to local development MongoDB of developer.
This mentioned on README page of [101rails](https://github.com/101companies/101rails)

# Restoring MongoDB

To restore MongoDB from backup you need to extract full_backup.zip from backup repo and execute next script in folder, were content of archive was extracted:

```
mongorestore --directoryperdb dump/wiki_production --drop
```

Be very carefully at this step!
It drops old db and replaces with dump!

Similar steps are used in script, that performs copying production db to local developer db.
https://github.com/101companies/101rails/blob/master/lib/tasks/push_db_to_github.rake#L36

# Implementation

Here will be described more technical details.

## Backup steps
- retrieve dump from production MongoDB instance 
- archive dump securing with password
- copy to backup folder
- commit content of backup folder to GitHub repo

## Deployment on production server

### Rails integration

For executing actions, described above were used **shared children** for deployed with Capistrano Rails application.

Were added next **shared children**:
- dump - for storing temporary dump of MongoDB
- dump_zip - folder, that 
- make_backup.sh script

### Cronjob

Example of cronjob executing every day at 3:00

```
0 3 * * * /path/to/the/script/make_backup.sh
```

For debugging is useful to use next line

```
0 3 * * * /path/to/the/script/make_backup.sh >> /path/to/logfile 2>&1
```

### Git credentials

To allow commit from server to github using github user credentials are stored in .netrc

```
machine github.com
    login 101commit
    password secret_password
```

### Backup script

This script will be executing on server to commit backup on server.
It doesn't contain any secret information, that's why it's listed as is.

```
#!/usr/bin/env bash
cd /home/user101/wiki/current/
source /home/user101/.bash_env
/usr/local/bin/bundle exec rake push_production_db_to_github
```

**Comment by rlaemmel** [comment]
Thanks for this documentation.
Closing thus.

**Comment by rlaemmel** [comment]
@mastermaiknemo can you please check that such backup actually works?

**Comment by mminski** [comment]
Hi Ralph,
i located the cronjob and script on the server, since the server has been down the database.zip in github was not updated anymore. This will change, when the server is running at 3.oo pm. Thats the time, when the cronjob is called.
Regards,

Michael
